DicleAcademyV2/Controllers/AbouteController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace DicleAcademy.Controllers
{
    public class AbouteController : Controller
    {
        private readonly IAboutUsService _abouteService;

        public AbouteController(IAboutUsService abouteService)
        {
            _abouteService = abouteService;
        }

        public IActionResult Index()
        {
          var aboute=  _abouteService.GetAllAboutUs();
            return View("AbouteIndex" , aboute);
        }
    }
}

DicleAcademyV2/Controllers/ContactController.cs
using Entities.ModelsDto;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace DicleAcademy.Controllers
{
    public class ContactController : Controller
    {
        private readonly IGetInTouchService _getInTouchService;
        private readonly IContactService _contactService;
        private readonly ICoursesService _coursesService;
        public ContactController(IGetInTouchService getInTouchService, IContactService contactService, ICoursesService coursesService)
        {
            _getInTouchService = getInTouchService;
            _contactService = contactService;
            _coursesService = coursesService;
        }

        public IActionResult Index()
        {
            var getInTouch = _getInTouchService.GetAllGetInTouch().FirstOrDefault();
            var courses = _coursesService.GetAllCourses();
            return View("ContactIndex", Tuple.Create(getInTouch, (List<CoursesDto>)courses));
        }
        [HttpPost]
        public IActionResult PostForm(ContactUsDto contactDto)
        {

            return RedirectToAction("Index");
        }
    }
}

DicleAcademyV2/Controllers/FooterController.cs
using Entities.Models;
using Entities.ModelsDto;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using Services.EFCore;

namespace DicleAcademyV2.Controllers
{
    public class FooterController : Controller
    {
        private readonly IGalleryService _galleryService;
        private readonly IContactService _contactService;   
        public FooterController(IGalleryService galleryService, IContactService contactService)
        {
            _galleryService = galleryService;
            _contactService = contactService;
        }
        public IActionResult Index()
        { //ContactDto
           var contact =  _contactService.GetAllContact();
            var gallery=  _galleryService.GetAllGallery();
            return PartialView(Tuple.Create((List<GalleryDto>)gallery, (List<ContactDto>)contact));
        }
    }
}

DicleAcademyV2/Controllers/TeamsController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace DicleAcademy.Controllers
{
    public class TeamsController : Controller
    {
        private readonly IInstructorsService _instructorsService;

        public TeamsController(IInstructorsService instructorsService)
        {
            _instructorsService = instructorsService;
        }

        public IActionResult Index()
        {
         var instruc= _instructorsService.GetAllInstructors();
            return View("TeamsIndex" , instruc);
        }
    }
}

DicleAcademyV2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>eLEARNING - eLearning HTML Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/assets/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/assets/lib/animate/animate.min.css" rel="stylesheet">
    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/assets/lib/owlcarousel/assets/owl.carousel.css" rel="stylesheet" />
    <!-- Template Stylesheet -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>
<body>
       <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->
    

    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a href="index.html" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>eLEARNING</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a asp-action="Index" asp-controller="Home" class="nav-item nav-link active">Home</a>
                <a asp-action="Index" asp-controller="Aboute" class="nav-item nav-link">About</a>
                <a asp-action="Index" asp-controller="Courses" class="nav-item nav-link">Courses</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a asp-action="Index" asp-controller="Teams" class="dropdown-item">Our Team</a>
                        <a asp-action="Index" asp-controller="Testimonial" class="dropdown-item">Testimonial</a>
                    </div>
                </div>
                <a asp-action="Index" asp-controller="Contact" class="nav-item nav-link">Contact</a>
            </div>
        </div>
    </nav>

    <!-- Carousel Start -->
    
        <main role="main" class="pb-3">
            @RenderBody()
        @Html.Action("Index","Footer")
        </main>



    <!-- Footer Start -->
    
   
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/lib/wow/wow.min.js"></script>
    <script src="~/assets/lib/easing/easing.min.js"></script>
    <script src="~/assets/lib/waypoints/waypoints.min.js"></script>
    <script src="~/assets/lib/owlcarousel/owl.carousel.min.js"></script>
    <!-- Template Javascript -->
    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>