DicleAcademyV2/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace DicleAcademy.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICoursesCategoriesService _coursesCategoriesService;

        public CategoryController(ICoursesCategoriesService coursesCategoriesService)
        {
            _coursesCategoriesService = coursesCategoriesService;
        }

        public IActionResult Index()
        {
          var category=  _coursesCategoriesService.GetAllCoursesCategories();
            return View("CategoryIndex" , category);
        }
        public IActionResult CategoryDetails(int id)
        { //category detail
            return View("CategoryDetailsIndex");
        }
    }
}

DicleAcademyV2/Controllers/CoursesController.cs
using Entities.ModelsDto;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace DicleAcademy.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICoursesCategoriesService _coursesCategoriesService;
        private readonly ICourseDetailsService _courseDetailsService;
        private readonly IInstructorsService _instructorsService;
        private readonly ICoursesService _coursesService;

        public CoursesController(ICoursesCategoriesService coursesCategoriesService, ICourseDetailsService courseDetailsService, ICoursesService coursesService, IInstructorsService instructorsService)
        {
            _coursesCategoriesService = coursesCategoriesService;
            _courseDetailsService = courseDetailsService;
            _coursesService = coursesService;
            _instructorsService = instructorsService;
        }

        public IActionResult Index()
        {
           List<GetCategoryWithCoursesDto> getCategoryWithCoursesDto = new List<GetCategoryWithCoursesDto>();
            List<InstructorsDto> instructorsList = _instructorsService.GetAllInstructors().ToList();

            var data =  _coursesCategoriesService.GetAllCoursesCategories();

           foreach (var item in data) 
            {
                GetCategoryWithCoursesDto getCategoryWithCourses = new GetCategoryWithCoursesDto();

                var dto =  _coursesService.GetCoursesByCategoryId(item.CategoryId);
                getCategoryWithCourses.CategoryName = item.CategoryName;
                getCategoryWithCourses.Courses = dto;
                getCategoryWithCourses.CoursesCategory = item;
                getCategoryWithCoursesDto.Add(getCategoryWithCourses);
            }
            return View("CoursesIndex" , Tuple.Create((List<GetCategoryWithCoursesDto>)getCategoryWithCoursesDto , (List<CoursesCategoriesDto>)data, instructorsList));
        }
        public IActionResult CoursesDetails(int id)
        {
          var courses= _courseDetailsService.GetByIdCourseDetails(id);
            return View("CoursesDetails" , courses);
        }
    }
}

DicleAcademyV2/Views/Courses/CoursesDetails.cshtml
@model CourseDetailsDto
<link href="~/assets/css/coursesdetilscss/coursesdetailscss.css" rel="stylesheet" />
<div class="container-fluid bg-primary py-5 mb-5 page-header">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-10 text-center">
                <h1 class="display-3 text-white animated slideInDown">Courses</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center">
                        <li class="breadcrumb-item"><a class="text-white" asp-action="Index" asp-controller="Home">Home</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">Courses Details</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- product section -->
<div class="container-xxl py-5">
    <div class="product-container">

    <!-- left side -->
    <div class="img-card">
            <img src="~/assets/img/@Model.Image" alt="" id="featured-image">
    </div>
    <!-- Right side -->
    <div class="product-info">
        <h3>@Model.CourseName</h3>
           <p>@Model.CourseDescription</p>
        <div>
            <h5>Eğitim Türü</h5>
            <p>@Model.CourseLocation</p>
            <div class="delivery">
                    <h5>Eğitim Süresi</h5>
                <p>@Model.CourseDuration Saat</p>
            </div>   
        </div>
    </div>
    </div>
</div>
<!-- script tags -->
<script src="~/assets/js/coursesdetailsjs/cart.js"></script>

DicleAcademyV2/Views/Courses/CoursesIndex.cshtml
@model Tuple< List<GetCategoryWithCoursesDto> , List<CoursesCategoriesDto>, List<InstructorsDto>>
<div class="container-fluid bg-primary py-5 mb-5 page-header">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-10 text-center">
                <h1 class="display-3 text-white animated slideInDown">Courses</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center">
                        <li class="breadcrumb-item"><a class="text-white" asp-action="Index" asp-controller="Home">Home</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">Courses</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- Courses Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Courses</h6>

        </div>
        @foreach (var item in Model.Item1)
        {
            if (item.Courses.Count > 0)
            {
                <h1 class="text-center mb-5">@item.CategoryName</h1>
                <div class="row g-4 justify-content-center">
                    @foreach (var item2 in item.Courses)
                    {

                        <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                            <div class="course-item bg-light">
                                <div class="position-relative overflow-hidden">

                                    <img class="img-fluid" src="~/assets/img/course-1.jpg" alt="">
                                    <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                                        <a href="@Url.Action("CoursesDetails" , "Courses" , new {id=item2.CourseId})" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">Courses Details</a>
                                    </div>
                                </div>
                                <div class="text-center p-4 pb-0">

                                    <h5 class="mb-4">@item2.CourseName</h5>
                                </div>
                                <div class="d-flex border-top">
                                    <small class="flex-fill text-center border-end py-2">
                                        <i class="fa fa-user-tie text-primary me-2"></i>
                                        @{
                                            var instructors = Model.Item3.FirstOrDefault(c => c.InstructorId == item2.InstructorId);
                                            string instructorName = instructors != null ? instructors.InstructorName : "";
                                        }
                                        @instructorName
                                    </small>
                                    <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>@item2.CoursesDuration</small>
                                    <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>@item2.CoursesQuota Students</small>
                                </div>
                            </div>
                        </div>

                    }
                </div>
                <br />
                <br />
            }
        }
    </div>
</div>

<!-- Categories Start -->
<div class="container-xxl py-5 category">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Categories</h6>
            <h1 class="mb-5">Courses Categories</h1>
        </div>
        <div class="row g-3">
            <div class="col-lg-12 col-md-6">
                <div class="row g-3">

                    @foreach (var item in Model.Item1)
                    {
                        <div class="col-lg-6 col-md-12 wow zoomIn" data-wow-delay="0.1s">
                            <a class="position-relative d-block overflow-hidden" href="@Url.Action("CategoryDetails" , "Category" , new {id=item.CoursesCategory.CategoryId})">
                                <img style="object-fit:cover; width:600px; height:400px;" class="img-fluid" src="~/assets/img/@item.CoursesCategory.CategoryImage" alt="">
                                <div class="bg-white text-center position-absolute bottom-0 end-0 py-2 px-3" style="margin: 1px;">
                                    <h5 class="m-0">@item.CoursesCategory.CategoryName</h5>
                                    <small class="text-primary">@item.Courses.Count</small>
                                </div>
                            </a>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>